name: Presensi

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  presensi:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Script presensi
        run: |
          pip3 install -r requirements.txt
          python3 app.py
